Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "goyave")
Ingredient.create(name: "lemon")
Ingredient.create(name: "tonic")
Ingredient.create(name: "ananas")
Ingredient.create(name: "honey")
Ingredient.create(name: "champaign")
Ingredient.create(name: "strawberry")
Ingredient.create(name: "blueberry")
Ingredient.create(name: "lime")
Ingredient.create(name: "coconut milk")
